name: production-model-endpoint
description: "Production ML Model Endpoint - Single Active Deployment"

compute_type: aci  # Use ACI for production deployment
resource_requirements:
  cpu: 2
  memory_in_gb: 4

scaling:
  target_utilization: 70
  min_replicas: 1
  max_replicas: 1  # Reduced for cost optimization

environment:
  name: production-model-env
  conda_file: environment.yml
  
inference_config:
  entry_script: score.py
  source_directory: ../src/

health_probe:
  initial_delay: 15  # Increased for production stability
  period: 10
  timeout: 5  # Increased timeout
  failure_threshold: 3

data_collection:
  enabled: true
  destination: production-model-data-collection

# Production-specific settings
production_settings:
  enable_app_insights: true
  enable_model_data_collection: true
  enable_authentication: false  # Set to true if auth is needed
  tags:
    environment: production
    deployment_type: single_endpoint
    auto_cleanup: false