compute_targets:
  training:
    name: "cpu-cluster"
    type: "AmlCompute"
    vm_size: "STANDARD_D2_V2"
    min_nodes: 0
    max_nodes: 4
    idle_seconds_before_scaledown: 120
  
  inference:
    name: "inference-cluster"
    type: "AksCompute"
    vm_size: "Standard_F4s_v2"
    agent_count: 3