name: ML Pipeline - Train and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  # workflow_dispatch:
  #   inputs:
  #     deploy_to_production:
  #       description: 'Deploy to production'
  #       required: false
  #       default: false
  #       type: boolean

jobs:
  data-validation: 
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data validation
      run: |
        python -m pytest tests/test_data_validation.py -v
      continue-on-error: false

  model-training:
    needs: data-validation
    runs-on : ubuntu-latest
    outputs:
        model-version: ${{ steps.train.outputs.model-version }}

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Azure ML workspace
        run: |
          python scripts/create_workspace_config.py
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}


    