name: ML Pipeline - Train and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  # workflow_dispatch:
  #   inputs:
  #     deploy_to_production:
  #       description: 'Deploy to production'
  #       required: false
  #       default: false
  #       type: boolean

jobs:
  data-validation: 
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data validation
      run: |
        python -m pytest tests/test_data_validation.py -v
      continue-on-error: false

  model-training:
    needs: data-validation
    runs-on : ubuntu-latest
    outputs:
        model-version: ${{ steps.train.outputs.model-version }}

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Azure ML workspace
        run: |
          python scripts/create_workspace_config.py
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}

      - name: Submit Model Training Job
        id: train
        run : | 
          python azure_ml/train_job.py \
          --experiment-name "model-training-$(date +%Y%m%d)" \
          --compute-name cpu-cluster \
          --vm-size STANDARD_DS3_V2 \
          --model-type random_forest \
          --model-name ${{ env.MODEL_NAME }} \
          --wait-for-completion
          
          # Extract model version from training output
          MODEL_VERSION=$(date +%Y%m%d%H%M%S)
          echo "model-version=$MODEL_VERSION" >> $GITHUB_OUTPUT

        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}


    