name: Model Monitoring and Data Drift Detection

# on:
#   schedule:
#     # Run every day at 2 AM UTC
#     - cron: '0 2 * * *'
#   workflow_dispatch:

on:
  push:
    branches: [ main, develop ]

env:
  AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  data-drift-detection:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Azure ML workspace
      run: |
        python scripts/create_workspace_config.py
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}
    
    - name: Run data drift detection
      run: |
        python monitoring/data_drift_detector.py
      continue-on-error: true
    
    - name: Upload drift reports
      uses: actions/upload-artifact@v4
      with:
        name: drift-reports
        path: outputs/drift_reports/

  model-performance-monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Monitor model performance
      run: |
        python monitoring/model_monitor.py
      continue-on-error: true
    
    - name: Upload performance reports
      uses: actions/upload-artifact@v4
      with:
        name: performance-reports
        path: outputs/performance_reports/

  alert-on-issues:
    needs: [data-drift-detection, model-performance-monitoring]
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
    - name: Send alert
      run: |
        echo "Model monitoring detected issues. Check the reports."
        # Add notification logic here (Slack, email, etc.)
